# Generated by Django 3.1.3 on 2020-11-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=280)),
                ('model', models.CharField(max_length=280)),
                ('year', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('vendor', 'model', 'year')},
            },
        ),
    ]
