# Generated by Django 3.1.3 on 2020-11-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('vendor', 'model', 'year')},
        ),
    ]
